### ISSUE TITLE
input data generating steps are not working properly

### ISSUE THREAD

**Issue by Sathiyarajan** [sahilbhange/SCD-2#1]
@sahilbhange Thanks for the informative tutorial.
DDL part is working fine but I could not proceed with the data load due to the following issues in the data generation.
I am getting the error while running the follwing command.
python Yelp_user.py 
Traceback (most recent call last):
  File "Yelp_user.py", line 36, in <module>
    'compliment_photos'
  File "/root/miniconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 2981, in __getitem__
    indexer = self.loc._convert_to_indexer(key, axis=1, raise_missing=True)
  File "/root/miniconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1271, in _convert_to_indexer
    return self._get_listlike_indexer(obj, axis, **kwargs)[1]
  File "/root/miniconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1078, in _get_listlike_indexer
    keyarr, indexer, o._get_axis_number(axis), raise_missing=raise_missing
  File "/root/miniconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1171, in _validate_read_indexer
    raise KeyError("{} not in index".format(not_found))
KeyError: "['compliment_writer', 'review_count', 'compliment_profile', 'compliment_photos', 'compliment_note', 'compliment_funny', 'compliment_more', 'compliment_hot', 'funny', 'fans', 'compliment_list', 'cool', 'compliment_cute', 'compliment_plain', 'compliment_cool'] not in index"

If you push out the data for the SCD it will be useful for me to proceed further.

**Comment by sahilbhange** [comment]
Hi @Sathiyarajan,

I downloaded the csv data from below link
https://www.kaggle.com/yelp-dataset/yelp-dataset/version/6#yelp_user.csv

I downloaded the recent file from above and ran the code, and it worked fine.

For below error:
File "Yelp_user.py", line 36, in 
'compliment_photos'
File "/root/miniconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 2981, in getitem
indexer = self.loc._convert_to_indexer(key, axis=1, raise_missing=True)

Can you try removing few columns like 'compliment_photos' and try loading file again? 
I did these data operations in Python3.6, not sure if the issue is with 3.7.

**Comment by sahilbhange** [comment]
No activity
